apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sales-storageclass 
provisioner: nfs.csi.k8s.io
parameters:
  server: 65.0.107.237
  share: /var/nfs/sales-microservice/test
reclaimPolicy: Retain
volumeBindingMode: Immediate