apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developer-binding
  namespace: sales-test-ns
subjects:
- kind: Group
  name: development
  apiGroup: rbac.authorization.k8s.io
- kind: ServiceAccount
  name: my-account
  namespace: sales-test-ns
roleRef:
  kind: Role
  name: developer-role
  apiGroup: rbac.authorization.k8s.io