apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: test-ns
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app: nginx-new
            topologyKey: kubernetes.io/hostname
      containers:
      - name: mysql-container
        image: mysql
        ports:
        - containerPort: 3306
    